# Generated by Django 3.1.1 on 2020-11-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kito', '0002_auto_20201105_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='kito',
            name='post_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
