# Generated by Django 3.1.1 on 2020-11-06 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kito', '0003_kito_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SameEat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('post_slug', models.SlugField(blank=True, null=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='kito/')),
                ('content', models.TextField(max_length=1000)),
                ('calories', models.IntegerField(default=1)),
                ('total_fat', models.IntegerField(default=1)),
                ('total_carbohydrate', models.IntegerField(default=1)),
                ('protein', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
