# Generated by Django 3.1.1 on 2020-11-07 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kito', '0004_sameeat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kito',
            old_name='titel',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='sameeat',
            old_name='titel',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='sameeat',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='sameeat',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='sameeat',
            name='total_carbohydrate',
        ),
        migrations.RemoveField(
            model_name='sameeat',
            name='total_fat',
        ),
    ]
