# Generated by Django 3.1.1 on 2020-11-07 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kito', '0005_auto_20201107_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kito',
            name='owner',
        ),
        migrations.AddField(
            model_name='kito',
            name='userheader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userheader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sameeat',
            name='image',
            field=models.ImageField(upload_to='cook/'),
        ),
        migrations.CreateModel(
            name='header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='header/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('post_slug', models.SlugField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
