# Generated by Django 3.1.1 on 2020-11-07 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kito', '0006_auto_20201107_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='kito',
            name='userheader',
        ),
        migrations.AddField(
            model_name='header',
            name='userheader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userheader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kito',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
